server:
  #端口号
  port: 8092
# 数据源、视图配置
spring:
  application:
      name: beyondbit-ias-admin
  profiles:
    active: buasso
  #配置用户授权  buasso使用研发  default 使用ias自带:buasso
  datasource:
    name: LIANGHUI
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.12.16:5236
    username: LIANGHUI
    password: LIANGHUI123456
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 8           # Redis服务器数据库
    host: 192.168.20.3
    password: gumis2017
    port: 6379
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  jmx:
    default-domain: ${spring.application.name}
    enabled: false
#  session:
#    store-type: redis


# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.beyondbit.ias.*.entity
  configuration:
    map-underscore-to-camel-case: true
  configuration-properties: { dbSchema: LIANGHUI. }

pagehelper:
  helperDialect: sqlserver
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
#server port
logging:
  file: beyondbit-ias-admin.log
  level:
logging.level.com.beyondbit.ias.admin.dao: debug
thymeleaf:
  cache: false

eureka:
  client:
    service-url:
      defaultZone:  http://192.168.20.3:1200/serviceRegistry/eureka
  instance:
    prefer-ip-address: true

#SSO
sso:
  signOnUrl: http://192.168.20.3:1200/sso/signOn
  signOutUrl: http://192.168.20.3:1200/sso/signOut
  excludeUrls: /js/*;/webjars/*;/font/*;/auditlog/*;/message/*;
  apiUrl: http://192.168.20.3:1200/sso/api

ias-security:
  signOnUrl: /login
  excludeUrls: /message/*;/webjars/**;/**;
  adminRole: admin