server:
  #端口号
  port: 8091
  servlet:
    session:
      cookie:
        http-only: true
        #指定path 为根路径
        path: /
# 数据源、视图配置
spring:
  application:
    name: beyondbit-ias-admin
  profiles:
    #配置 用户授权  buasso 使用研发  default 使用ias自带
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.52.219.125:3306/pdfl?serverTimezone=GMT&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: robustsoft
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0           # Redis服务器数据库
    host: 192.168.23.23
    password: gumis2017
    port: 6379
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  jmx:
    default-domain: ${spring.application.name}
    enabled: false
  session:
    store-type: redis

# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.beyondbit.ias.*.entity
  configuration:
    map-underscore-to-camel-case: true
  configuration-properties: { dbSchema: pdfl. }

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
#server port
logging:
  file: beyondbit-ias-admin.log
  level:
logging.level.com.beyondbit.ias.admin.dao: debug
thymeleaf:
  cache: false
eureka:
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server上，默认为true
    fetch-registry: false       #表示是否从Eureka Server上获取注册信息，默认为true
#文件上传路径
upload:
  fileUploadPath: C:\迅雷下载\Attachments\
  chunkSize: 5 242 880